#!/bin/bash
# QUICK START - Unix V6 x86 Kernel Build
# Copy and paste these commands in order

echo "=== Unix V6 x86 Kernel - Quick Start Guide ==="
echo ""
echo "STEP 1: Install dependencies (Ubuntu/Debian)"
echo "================================================"
echo "sudo apt-get update && sudo apt-get install -y \\"
echo "    build-essential gcc-multilib g++-multilib binutils \\"
echo "    bison flex wget curl grub-common grub-pc-bin xorriso"
echo ""
echo "Alternatively, run the automated setup:"
echo "    chmod +x /workspaces/unix-v6/kernel/setup-unix-v6-build.sh"
echo "    /workspaces/unix-v6/kernel/setup-unix-v6-build.sh"
echo ""
echo "================================================"
echo ""
echo "STEP 2: Build the kernel"
echo "================================================"
echo "cd /workspaces/unix-v6/kernel"
echo "make clean"
echo "make build"
echo ""
echo "Expected output:"
echo "  i686-elf-as --32 -o boot.o boot.S"
echo "  i686-elf-gcc -ffreestanding -O2 -nostdlib -Wall -Wextra -c -o kernel.o kernel.c"
echo "  i686-elf-ld -T linker.ld -nostdlib -o kernel.elf boot.o kernel.o"
echo ""
echo "================================================"
echo ""
echo "STEP 3: Verify the ELF binary"
echo "================================================"
echo "file /workspaces/unix-v6/kernel/kernel.elf"
echo ""
echo "Expected output:"
echo "  kernel.elf: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV)..."
echo ""
echo "================================================"
echo ""
echo "STEP 4: Generate bootable ISO"
echo "================================================"
echo "cd /workspaces/unix-v6/kernel"
echo "make iso"
echo ""
echo "Expected output:"
echo "  mkdir -p isodir/boot/grub"
echo "  cp kernel.elf isodir/boot/kernel.elf"
echo "  cp grub.cfg isodir/boot/grub/grub.cfg"
echo "  grub-mkrescue -o unix_v6.iso isodir"
echo ""
echo "================================================"
echo ""
echo "STEP 5: Verify ISO image"
echo "================================================"
echo "ls -lh /workspaces/unix-v6/kernel/unix_v6.iso"
echo "file /workspaces/unix-v6/kernel/unix_v6.iso"
echo ""
echo "Expected: ISO 9660 CD-ROM filesystem data..."
echo ""
echo "================================================"
echo ""
echo "STEP 6: Test with QEMU (optional)"
echo "================================================"
echo "sudo apt-get install -y qemu-system-x86"
echo "qemu-system-i386 -cdrom /workspaces/unix-v6/kernel/unix_v6.iso"
echo ""
echo "Expected to see:"
echo "  - GRUB boot menu"
echo "  - Select 'Unix V6 x86'"
echo "  - White text on black background showing initialization messages"
echo ""
echo "================================================"
echo ""
echo "SUCCESS! Your bootable Unix V6 x86 ISO is ready!"
echo ""
