#ifndef _SYS_SYSCALL_H
#define _SYS_SYSCALL_H

/* Syscall numbers */
#define SYS_EXIT    1
#define SYS_FORK    2
#define SYS_READ    3
#define SYS_WRITE   4
#define SYS_OPEN    5
#define SYS_CLOSE   6
#define SYS_WAIT    7
#define SYS_CREAT   8
#define SYS_GETFBINFO 39
#define SYS_LSEEK   19
#define SYS_EXEC    11
#define SYS_CHDIR   12
#define SYS_GETPID  20
#define SYS_GETPPID 21
#define SYS_SETUID  23
#define SYS_GETUID  24
#define SYS_SETGID  46
#define SYS_KILL    37
#define SYS_GETGID  47
#define SYS_GETPGRP 48
#define SYS_GETCWD  49
#define SYS_EXIT2   50
#define SYS_TRUNCATE  51
#define SYS_FTRUNCATE 52
#define SYS_FSYNC     53
#define SYS_UTIME     54
#define SYS_PIPE      55
#define SYS_DUP       56
#define SYS_DUP2      57
#define SYS_STAT      58
#define SYS_FSTAT     59
#define SYS_LSTAT     60
#define SYS_LINK      61
#define SYS_UNLINK    62
#define SYS_RENAME    63
#define SYS_MKDIR     64
#define SYS_RMDIR     65
#define SYS_CHMOD     66
#define SYS_UMASK     67
#define SYS_BRK       68
#define SYS_SBRK      69
#define SYS_SIGACTION    70
#define SYS_SIGPROCMASK  71
#define SYS_SIGSUSPEND   72
#define SYS_ALARM     73
#define SYS_PAUSE     74
#define SYS_TIME      75
#define SYS_GETTIMEOFDAY 76
#define SYS_SLEEP     77
#define SYS_NANOSLEEP 78
#define SYS_TCGETATTR 79
#define SYS_TCSETATTR 80
#define SYS_TCFLUSH   81
#define SYS_IOCTL     82
#define SYS_SELECT    83
#define SYS_POLL      84
#define SYS_GETPGID   85
#define SYS_SETPGID   86
#define SYS_GETSID    87
#define SYS_SETSID    88
#define SYS_MMAP      89
#define SYS_MUNMAP    90
#define SYS_GETRLIMIT 91
#define SYS_SETRLIMIT 92
#define SYS_GETRUSAGE 93
#define SYS_CHOWN     94
#define SYS_LCHOWN    95
#define SYS_FCHOWN    96
#define SYS_FCHMOD    97
#define SYS_UTIMES    98
#define SYS_FCNTL     99
#define SYS_ACCESS    100
#define SYS_WAITPID   101
#define SYS_ISATTY    102
#define SYS_SIGPENDING 103
#define SYS_SIGRETURN 104
#define SYS_MPROTECT 105

#endif /* _SYS_SYSCALL_H */
